[default.extend-words]
Airmate = "Airmate"
airmate = "airmate"
AIRAC = "AIRAC"
Dynon = "Dynon"
SkyView = "SkyView"
navdata = "navdata"
aiofile = "aiofile"
vfat = "vfat"
Copie = "Copie"
reste = "reste"
"Vérif" = "Vérif"
"montée" = "montée"
absente = "absente"
